version: '3.2'
services:
  web:
    env_file:
    - ${ENV_FILE}
    container_name: ${REACT_APP_APP_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${REACT_APP_APP_PORT}:80